
AWSTemplateFormatVersion: "2010-09-09"
Description : "api gateway for the health customer retention model"
Resources:
  RetentionApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "access to the health customer retention model"
      Name: "health-customer-retention"

  v1ApiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: 
        Ref: "RetentionApi"
      ParentId:
        Fn::GetAtt: 
          - "RetentionApi"
          - "RootResourceId"
      PathPart: "v1"

  retentionApiResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        RestApiId: 
          Ref: "RetentionApi"
        ParentId:
          Ref: "v1ApiResource"
        PathPart: "retention"

  calcHealthCustomerProbApiResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        RestApiId: 
          Ref: "RetentionApi"
        ParentId:
          Ref: "retentionApiResource"
        PathPart: "calculate-health-customer-probability"

  lambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:invokeFunction"
      FunctionName: "arn:aws:lambda:us-east-1:431854676248:function:customer-retention"
      Principal: "apigateway.amazonaws.com"
      SourceAccount: 
        Ref: "AWS::AccountId"


  postCalculateHealthCustomerProbabilityMethod:
    DependsOn: "lambdaPermission"
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: NONE
      ApiKeyRequired: TRUE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: "AWS_PROXY"
        Uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:431854676248:function:customer-retention/invocations"
        # Uri: Fn::Join
        #   - ""
        #   - "arn:aws:apigateway:us-east-1:lambda:path/"
        #   - "2015-03-31/functions/"
        #   Fn::GetAtt ["customer-retention", "Arn"]
        #   - "/invocations"
         # - "arn:aws:lambda:us-east-1:431854676248:function:customer-retention"
# arn:aws:apigateway:region:lambda:path/{path}
# {path} = /2015-03-31/functions/{LambdaFunctionARN}/invocations
      ResourceId: !Ref calcHealthCustomerProbApiResource
      RestApiId: !Ref RetentionApi

  Deployment:
    DependsOn: "postCalculateHealthCustomerProbabilityMethod"
    Type: "AWS::ApiGateway::Deployment"
    Properties: 
      RestApiId: 
        Ref: "RetentionApi"

  UatStage:
    Type: "AWS::ApiGateway::Stage"
    Properties:
      StageName: uat
      Description: Uat stage
      RestApiId: !Ref RetentionApi
      DeploymentId: !Ref Deployment
      MethodSettings:
        - ResourcePath: /uat
          HttpMethod: POST
          MetricsEnabled: 'true'
          DataTraceEnabled: 'true'
          ThrottlingBurstLimit: '999'

Outputs:
  StackName:
    Value: !Ref AWS::StackName
    Description: "Stack Name"
  RetentionApi:
    Value: !Ref RetentionApi
    Description: "Retention API ID"
  v1ApiResource:
    Value: !Ref v1ApiResource
    Description: "V1 api resource id"