
AWSTemplateFormatVersion: "2010-09-09"
Description : "api gateway for the health customer retention model"
Resources:
  RetentionApi:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Description: "access to the health customer retention model"
      Name: "health-customer-retention"

  v1ApiResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: 
        Ref: "RetentionApi"
      ParentId:
        Fn::GetAtt: 
          - "RetentionApi"
          - "RootResourceId"
      PathPart: "v1"

  retentionApiResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        RestApiId: 
          Ref: "RetentionApi"
        ParentId:
          Ref: "v1ApiResource"
        PathPart: "retention"

  calcHealthCustomerProbApiResource:
      Type: "AWS::ApiGateway::Resource"
      Properties:
        RestApiId: 
          Ref: "RetentionApi"
        ParentId:
          Ref: "retentionApiResource"
        PathPart: "calculate-health-customer-probability"


Outputs:
  StackName:
    Value: !Ref AWS::StackName
    Description: "Stack Name"
  RetentionApi:
    Value: !Ref RetentionApi
    Description: "Retention API ID"
  v1ApiResource:
    Value: !Ref v1ApiResource
    Description: "V1 api resource id"